name: Draft Release

on:
  push:
    branches: [main]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}